### ISSUE TITLE
setuptools requirement

### ISSUE THREAD

**Issue by Sean-Morrison** [sdss/semaphore#2]
this package has a hidden dependency of setuptools <=66.1.1. With 66.2.0 "pkg_resources is deprecated as an API".

**Comment by ajwheeler** [comment]
Just noting that I hit this as well.  For others, the error looks like
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/awheeler/Simons Foundation Dropbox/Adam Wheeler/science/rotating_giants/.venv/lib/python3.12/site-packages/sdss_semaphore/__init__.py", line 6, in <module>
    from pkg_resources import resource_filename
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by ajwheeler** [comment]
Workaround of `uv pip install 'setuptools<=66.1.1'` worked.

**Comment by Sean-Morrison** [comment]
the other option seems to be to use importlib

import importlib.resources as resources

try: #python 3.9+
    path = resources.as_file(resources.files(__name__).joinpath(f'etc/{self.MAPPING_BASENAME}')) 
except: #python 3.7 and 3.8
    path = resources.path(__name__, f'etc/{self.MAPPING_BASENAME}')

**Comment by Sean-Morrison** [comment]
Fixed in 0.2.5
